name: Flang Tests

on:
  push:
    branches:
      - fir-dev
    paths:
      - 'flang/**'
      - '.github/workflows/flang-tests.yml'
  pull_request:
    branches:
      - fir-dev
    paths:
      - 'flang/**'
      - '.github/workflows/flang-tests.yml'

jobs:
  build_flang:
    name: flang check-flang
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
    steps:
    - name: Install Ninja
      uses: llvm/actions/install-ninja@main
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test flang
      uses: llvm/actions/build-test-llvm-project@main
      with:
        cmake_args: -G Ninja -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_PARALLEL_COMPILE_JOBS=2 -DLLVM_ENABLE_PROJECTS="clang;flang;mlir" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host
        build_target: check-flang
